package com.example.fightingflow.util.characterData

import com.example.fightingflow.R
import com.example.fightingflow.model.CharacterEntry
import com.example.fightingflow.util.ImmutableList

val streetFighter6Characters = ImmutableList(
    listOf(
        CharacterEntry(
            name = "A.K.I.",
            imageId = R.drawable.aki,
            fightingStyle = "Snake Kung Fu",
            uniqueMoves = "Nightshade Pulse, Serpent Strike, Toxic Blossom",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Akuma",
            imageId = R.drawable.akuma,
            fightingStyle = " Satsui no Hado, Ansatsuken",
            uniqueMoves = "Gohadoken, Zanku Hadoken, Tatsumaki Zankukyaku, Ashura Senku",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Blanka",
            imageId = R.drawable.blanka,
            fightingStyle = "Feral movement, electric attacks",
            uniqueMoves = "Electric Thunder, Rolling Attack, Vertical Rolling",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Cammy",
            imageId = R.drawable.cammy,
            fightingStyle = "Shadaloo fighting techniques (Shadaloo)" +
                    "Special Forces training (Delta Red)",
            uniqueMoves = "Spiral Arrow, Cannon Spike, Hooligan Combination",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Chun-Li",
            imageId = R.drawable.chunli,
            fightingStyle = "Chinese martial arts/Kung Fu and Tai Chi",
            uniqueMoves = "Kikoken, Spinning Bird Kick, Hyakuretsukyaku",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Dee Jay",
            imageId = R.drawable.deejay,
            fightingStyle = "Kickboxing and break dancing",
            uniqueMoves = "Max Out, Machinegun Upper, Rolling Sobat",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Dhalsim",
            imageId = R.drawable.dhalsim,
            fightingStyle = "Esoteric Yoga",
            uniqueMoves = "Yoga Fire, Yoga Flame, Yoga Teleport",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "E. Honda",
            imageId = R.drawable.ehonda,
            fightingStyle = "Sumo Wrestler Chef",
            uniqueMoves = "Hundred Hand Slap, Sumo Headbutt, Oicho Throw",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Ed",
            imageId = R.drawable.ed,
            fightingStyle = "Psycho Boxing",
            uniqueMoves = "Psycho Flicker, Psycho Rising, Psycho Smash",
            game = "Street Fighter",
            entry = "6",
        ),CharacterEntry(
            name = "Elena",
            imageId = R.drawable.elena,
            fightingStyle = "Capoeira Master",
            uniqueMoves = "Meteor Volley, Revival Dance, Song of the Grasslands",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Guile",
            imageId = R.drawable.guile,
            fightingStyle = "Martial arts and professional wrestling",
            uniqueMoves = "Sonic Boom, Flash Kick",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Jamie",
            imageId = R.drawable.jamie,
            fightingStyle = "Zui Quan (Drunken Fist) & Breakdancing",
            uniqueMoves = "Luminous Dive Kick, Swagger Step, Bakkai",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "JP",
            imageId = R.drawable.jp,
            fightingStyle = "Bartitsu & Psycho Power",
            uniqueMoves = "Triglav, Departure, Embrace",
            game = "Street Fighter 6",
            entry = "6",
        ),
        CharacterEntry(
            name = "Juri",
            imageId = R.drawable.juri,
            fightingStyle = "Taekwondo, ki attacks",
            uniqueMoves = "Fuharenkyaku, Kasatsushu, Ankensatsu",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Ken",
            imageId = R.drawable.ken,
            fightingStyle = "Karate based martial arts, Ansatsuken",
            uniqueMoves = "Hadoken, Shoryuken, Tatsumaki Senpukyaku, Quick Dash",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Kimberly",
            imageId = R.drawable.kimberly,
            fightingStyle = "Bushin-ryu Ninjutsu",
            uniqueMoves = "Sprint, Genius at Play, Bushin Beats",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Lily",
            imageId = R.drawable.lily,
            fightingStyle = "Thunderfoot Martial Arts",
            uniqueMoves = "Condor Dive, Condor Spire, Tomahawk Buster",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Luke",
            imageId = R.drawable.luke,
            fightingStyle = "Military MMA",
            uniqueMoves = "Sand Blaster, Rising Uppercut, Flash Knuckle",
            game = "Street Fighter",
            entry = "6"
        ),
        CharacterEntry(
            name = "M.Bison",
            imageId = R.drawable.m_bison,
            fightingStyle = "Psycho Power & Lerdrit",
            uniqueMoves = " Knee Press Nightmare, Psycho Punisher, Unlimited Psycho Crusher",
            game = "Street Fighter",
            entry = "6"
        ),
        CharacterEntry(
            name = "Mai",
            imageId = R.drawable.mai,
            fightingStyle = "Shiranui-ryuu Ninjitsu",
            uniqueMoves = " Knee Press Nightmare, Psycho Punisher, Unlimited Psycho Crusher",
            game = "Street Fighter",
            entry = "6"
        ),
        CharacterEntry(
            name = "Manon",
            imageId = R.drawable.manon,
            fightingStyle = "Judo and ballet dancing",
            uniqueMoves = "Manège Doré, Pas de Deux, Renversé",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Marisa",
            imageId = R.drawable.marisa,
            fightingStyle = "Pankration",
            uniqueMoves = "Scutum, Phalanx, Gladius",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Rashid",
            imageId = R.drawable.rashid,
            fightingStyle = "Wind and parkour",
            uniqueMoves = "Whirlwind Shot, Arabian Cyclone, Eagle Spike",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Ryu",
            imageId = R.drawable.ryu,
            fightingStyle = "Ansatsuken",
            uniqueMoves = "Hadoken, Shoryuken, Tatsumaki Senpukyaku",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Terry",
            imageId = R.drawable.terry_bogard,
            fightingStyle = "Martial arts and Hakkyokuseiken chi techniques",
            uniqueMoves = " Buster Wolf, Power Geyser, Rising Fang",
            game = "Street Fighter",
            entry = "6",
        ),
        CharacterEntry(
            name = "Zangief",
            imageId = R.drawable.zangief,
            fightingStyle = "Mix of Russian and American pro wrestling",
            uniqueMoves = "Spinning Pile Driver, Siberian Express",
            game = "Street Fighter",
            entry = "6",
        ),
    )
)