package com.example.fightingflow.util.characterData

import com.example.fightingflow.R
import com.example.fightingflow.model.CharacterEntry
import com.example.fightingflow.model.MoveEntry
import com.example.fightingflow.util.ImmutableList

val streetFighter6Characters = ImmutableList(
    listOf(
        CharacterEntry(
            name = "A.K.I.",
            imageId = R.drawable.aki,
            fightingStyle = "Snake Kung Fu",
            uniqueMoves = "Nightshade Pulse, Serpent Strike, Toxic Blossom",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Akuma",
            imageId = R.drawable.akuma,
            fightingStyle = " Satsui no Hado, Ansatsuken",
            uniqueMoves = "Gohadoken, Zanku Hadoken, Tatsumaki Zankukyaku, Ashura Senku",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Blanka",
            imageId = R.drawable.blanka,
            fightingStyle = "Feral movement, electric attacks",
            uniqueMoves = "Electric Thunder, Rolling Attack, Vertical Rolling",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Cammy",
            imageId = R.drawable.cammy,
            fightingStyle = "Shadaloo fighting techniques (Shadaloo)" +
                    "Special Forces training (Delta Red)",
            uniqueMoves = "Spiral Arrow, Cannon Spike, Hooligan Combination",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Chun-Li",
            imageId = R.drawable.chunli,
            fightingStyle = "Chinese martial arts/Kung Fu and Tai Chi",
            uniqueMoves = "Kikoken, Spinning Bird Kick, Hyakuretsukyaku",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Dee Jay",
            imageId = R.drawable.deejay,
            fightingStyle = "Kickboxing and break dancing",
            uniqueMoves = "Max Out, Machinegun Upper, Rolling Sobat",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Dhalsim",
            imageId = R.drawable.dhalsim,
            fightingStyle = "Esoteric Yoga",
            uniqueMoves = "Yoga Fire, Yoga Flame, Yoga Teleport",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "E. Honda",
            imageId = R.drawable.ehonda,
            fightingStyle = "Sumo Wrestler Chef",
            uniqueMoves = "Hundred Hand Slap, Sumo Headbutt, Oicho Throw",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Ed",
            imageId = R.drawable.ed,
            fightingStyle = "Psycho Boxing",
            uniqueMoves = "Psycho Flicker, Psycho Rising, Psycho Smash",
            game = "Street Fighter VI",
        ),CharacterEntry(
            name = "Elena",
            imageId = R.drawable.elena,
            fightingStyle = "Capoeira Master",
            uniqueMoves = "Meteor Volley, Revival Dance, Song of the Grasslands",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Guile",
            imageId = R.drawable.guile,
            fightingStyle = "Martial arts and professional wrestling",
            uniqueMoves = "Sonic Boom, Flash Kick",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Jamie",
            imageId = R.drawable.jamie,
            fightingStyle = "Zui Quan (Drunken Fist) & Breakdancing",
            uniqueMoves = "Luminous Dive Kick, Swagger Step, Bakkai",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "JP",
            imageId = R.drawable.jp,
            fightingStyle = "Bartitsu & Psycho Power",
            uniqueMoves = "Triglav, Departure, Embrace",
            game = "Street Fighter VI 6",
        ),
        CharacterEntry(
            name = "Juri",
            imageId = R.drawable.juri,
            fightingStyle = "Taekwondo, ki attacks",
            uniqueMoves = "Fuharenkyaku, Kasatsushu, Ankensatsu",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Ken",
            imageId = R.drawable.ken,
            fightingStyle = "Karate based martial arts, Ansatsuken",
            uniqueMoves = "Hadoken, Shoryuken, Tatsumaki Senpukyaku, Quick Dash",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Kimberly",
            imageId = R.drawable.kimberly,
            fightingStyle = "Bushin-ryu Ninjutsu",
            uniqueMoves = "Sprint, Genius at Play, Bushin Beats",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Lily",
            imageId = R.drawable.lily,
            fightingStyle = "Thunderfoot Martial Arts",
            uniqueMoves = "Condor Dive, Condor Spire, Tomahawk Buster",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Luke",
            imageId = R.drawable.luke,
            fightingStyle = "Military MMA",
            uniqueMoves = "Sand Blaster, Rising Uppercut, Flash Knuckle",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "M.Bison",
            imageId = R.drawable.m_bison,
            fightingStyle = "Psycho Power & Lerdrit",
            uniqueMoves = " Knee Press Nightmare, Psycho Punisher, Unlimited Psycho Crusher",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Mai",
            imageId = R.drawable.mai,
            fightingStyle = "Shiranui-ryuu Ninjitsu",
            uniqueMoves = " Knee Press Nightmare, Psycho Punisher, Unlimited Psycho Crusher",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Manon",
            imageId = R.drawable.manon,
            fightingStyle = "Judo and ballet dancing",
            uniqueMoves = "Manège Doré, Pas de Deux, Renversé",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Marisa",
            imageId = R.drawable.marisa,
            fightingStyle = "Pankration",
            uniqueMoves = "Scutum, Phalanx, Gladius",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Rashid",
            imageId = R.drawable.rashid,
            fightingStyle = "Wind and parkour",
            uniqueMoves = "Whirlwind Shot, Arabian Cyclone, Eagle Spike",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Ryu",
            imageId = R.drawable.ryu,
            fightingStyle = "Ansatsuken",
            uniqueMoves = "Hadoken, Shoryuken, Tatsumaki Senpukyaku",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Terry",
            imageId = R.drawable.terry_bogard,
            fightingStyle = "Martial arts and Hakkyokuseiken chi techniques",
            uniqueMoves = " Buster Wolf, Power Geyser, Rising Fang",
            game = "Street Fighter VI",
        ),
        CharacterEntry(
            name = "Zangief",
            imageId = R.drawable.zangief,
            fightingStyle = "Mix of Russian and American pro wrestling",
            uniqueMoves = "Spinning Pile Driver, Siberian Express",
            game = "Street Fighter VI",
        ),
    )
)

val streetFighterVIMoves = ImmutableList(
    listOf(
        // Basic Inputs
        MoveEntry(moveName = "Light Punch", notation = "LP", moveType = "Normal", associatedCharacter = "Generic"),
        MoveEntry(moveName = "Medium Punch", notation = "MP", moveType = "Normal", associatedCharacter = "Generic"),
        MoveEntry(moveName = "Heavy Punch", notation = "HP", moveType = "Normal", associatedCharacter = "Generic"),
        MoveEntry(moveName = "Light Kick", notation = "LK", moveType = "Normal", associatedCharacter = "Generic"),
        MoveEntry(moveName = "Medium Kick", notation = "MK", moveType = "Normal", associatedCharacter = "Generic"),
        MoveEntry(moveName = "Heavy Kick", notation = "HK", moveType = "Normal", associatedCharacter = "Generic"),
        MoveEntry(moveName = "Drive Impact", notation = "HP + HK", moveType = "Drive", counterHit = true, associatedCharacter = "Generic"),
        MoveEntry(moveName = "Drive Parry", notation = "MP + MK", moveType = "Drive", associatedCharacter = "Generic"),
        MoveEntry(moveName = "Perfect Parry", notation = "(Tap) MP + MK", moveType = "Drive", justFrame = true, associatedCharacter = "Generic"),
        MoveEntry(moveName = "Drive Rush", notation = "→→ or Parry + →", moveType = "Drive", associatedCharacter = "Generic"),
        MoveEntry(moveName = "Drive Reversal", notation = "(Guard) → + HP + HK", moveType = "Drive", associatedCharacter = "Generic"),
        MoveEntry(moveName = "Overdrive (OD) Move", notation = "Special Move + PP or KK", moveType = "Overdrive", associatedCharacter = "Generic"),
        MoveEntry(moveName = "Super Art 1", notation = "SA Input + P", moveType = "Super Art", associatedCharacter = "Generic"),
        MoveEntry(moveName = "Super Art 2", notation = "SA Input + P", moveType = "Super Art", associatedCharacter = "Generic"),
        MoveEntry(moveName = "Super Art 3", notation = "SA Input + P or K", moveType = "Super Art", associatedCharacter = "Generic"),

        // A.K.I.
        MoveEntry(moveName = "Snake Step", notation = "↓ ↘ → + K", moveType = "Special", associatedCharacter = "A.K.I."),
        MoveEntry(moveName = "OD Snake Step", notation = "↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "A.K.I."),
        MoveEntry(moveName = " noxious breath", notation = "↓ ↙ ← + P", moveType = "Special", associatedCharacter = "A.K.I."),
        MoveEntry(moveName = "OD noxious breath", notation = "↓ ↙ ← + PP", moveType = "Overdrive", associatedCharacter = "A.K.I."),
        MoveEntry(moveName = "clutch", notation = "→ ↓ ↘ + P", moveType = "Special", associatedCharacter = "A.K.I."),
        MoveEntry(moveName = "OD clutch", notation = "→ ↓ ↘ + PP", moveType = "Overdrive", associatedCharacter = "A.K.I."),
        MoveEntry(moveName = "orphaned", notation = "← ↙ ↓ ↘ → + K", moveType = "Special", associatedCharacter = "A.K.I."),
        MoveEntry(moveName = "OD orphaned", notation = "← ↙ ↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "A.K.I."),
        MoveEntry(moveName = "SA1 - toxic blossom", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "A.K.I."),
        MoveEntry(moveName = "SA2 - deadly imprint", notation = "↓ ↙ ← ↓ ↙ ← + K", moveType = "Super Art", associatedCharacter = "A.K.I."),
        MoveEntry(moveName = "SA3 - sinner's salvation", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "A.K.I."),

        // Blanka
        MoveEntry(moveName = "Rolling Attack", notation = "← (charge) → + P", moveType = "Special", hold = true, associatedCharacter = "Blanka"),
        MoveEntry(moveName = "OD Rolling Attack", notation = "← (charge) → + PP", moveType = "Overdrive", hold = true, associatedCharacter = "Blanka"),
        MoveEntry(moveName = "Vertical Rolling", notation = "↓ (charge) ↑ + K", moveType = "Special", hold = true, associatedCharacter = "Blanka"),
        MoveEntry(moveName = "OD Vertical Rolling", notation = "↓ (charge) ↑ + KK", moveType = "Overdrive", hold = true, associatedCharacter = "Blanka"),
        MoveEntry(moveName = "Blanka Ball", notation = "↓ ↘ → + K", moveType = "Special", associatedCharacter = "Blanka"),
        MoveEntry(moveName = "OD Blanka Ball", notation = "↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Blanka"),
        MoveEntry(moveName = "Wild Lift", notation = "(After Coward Crouch) + P", moveType = "Special", associatedCharacter = "Blanka"),
        MoveEntry(moveName = "OD Wild Lift", notation = "(After Coward Crouch) + PP", moveType = "Overdrive", associatedCharacter = "Blanka"),
        MoveEntry(moveName = "Raid Jump", notation = "(After Coward Crouch) + K", moveType = "Special", associatedCharacter = "Blanka"),
        MoveEntry(moveName = "OD Raid Jump", notation = "(After Coward Crouch) + KK", moveType = "Overdrive", associatedCharacter = "Blanka"),
        MoveEntry(moveName = "Coward Crouch", notation = "↓ + PP", moveType = "Special", associatedCharacter = "Blanka"),
        MoveEntry(moveName = "SA1 - Lightning Beast", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Blanka"),
        MoveEntry(moveName = "SA2 - Ground Shave Rolling", notation = "← ↙ ↓ ↘ → ← ↙ ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Blanka"),
        MoveEntry(moveName = "SA3 - Jungle Dynamo", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", hold = true, associatedCharacter = "Blanka"),

        // Cammy
        MoveEntry(moveName = "Spiral Arrow", notation = "↓ ↘ → + K", moveType = "Special", hold = true, associatedCharacter = "Cammy"),
        MoveEntry(moveName = "OD Spiral Arrow", notation = "↓ ↘ → + KK", moveType = "Overdrive", hold = true, associatedCharacter = "Cammy"),
        MoveEntry(moveName = "Cannon Spike", notation = "→ ↓ ↘ + K", moveType = "Special", hold = true, associatedCharacter = "Cammy"),
        MoveEntry(moveName = "OD Cannon Spike", notation = "→ ↓ ↘ + KK", moveType = "Overdrive", hold = true, associatedCharacter = "Cammy"),
        MoveEntry(moveName = "Quick Spin Knuckle", notation = "QCB + P", moveType = "Special", associatedCharacter = "Cammy"),
        MoveEntry(moveName = "OD Quick Spin Knuckle", notation = "QCB + PP", moveType = "Overdrive", associatedCharacter = "Cammy"),
        MoveEntry(moveName = "Cannon Strike", notation = "(in air) ↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Cammy"),
        MoveEntry(moveName = "OD Cannon Strike", notation = "(in air) ↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Cammy"),
        MoveEntry(moveName = "Hooligan Combination", notation = "QCF + P", moveType = "Special", associatedCharacter = "Cammy"),
        MoveEntry(moveName = "OD Hooligan Combination", notation = "QCF + PP", moveType = "Overdrive", associatedCharacter = "Cammy"),
        MoveEntry(moveName = "SA1 - Killer Bee Spin", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Cammy"),
        MoveEntry(moveName = "SA2 - CQC", notation = "↓ ↙ ← ↓ ↙ ← + K", moveType = "Super Art", associatedCharacter = "Cammy"),
        MoveEntry(moveName = "SA3 - Delta Red Assault", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Cammy"),

        // Chun-Li
        MoveEntry(moveName = "Kikoken", notation = "← (charge) → + P", moveType = "Special", hold = true, associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "OD Kikoken", notation = "← (charge) → + PP", moveType = "Overdrive", hold = true, associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "Hundred Lightning Kicks", notation = "↓ ↘ → + K", moveType = "Special", associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "OD Hundred Lightning Kicks", notation = "↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "Aerial Hundred Lightning Kicks", notation = "(in air) ↓ ↘ → + K", moveType = "Special", associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "OD Aerial Hundred Lightning Kicks", notation = "(in air) ↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "Spinning Bird Kick", notation = "↓ (charge) ↑ + K", moveType = "Special", hold = true, associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "OD Spinning Bird Kick", notation = "↓ (charge) ↑ + KK", moveType = "Overdrive", hold = true, associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "Hazanshu", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "OD Hazanshu", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "Tensho Kicks", notation = "↓ ↓ + K", moveType = "Special", associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "OD Tensho Kicks", notation = "↓ ↓ + KK", moveType = "Overdrive", associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "SA1 - Kikosho", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "SA2 - Aerial Kikosho", notation = "(in air) ↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "SA3 - Hoyoku-sen", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Chun-Li"),
        MoveEntry(moveName = "SA3 - Soten Ranka", notation = "← ↙ ↓ ↘ → ← ↙ ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Chun-Li"),

        // Dhalsim
        MoveEntry(moveName = "Yoga Fire", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "Dhalsim"),
        MoveEntry(moveName = "OD Yoga Fire", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Dhalsim"),
        MoveEntry(moveName = "Yoga Flame", notation = "← ↙ ↓ ↘ → + P", moveType = "Special", associatedCharacter = "Dhalsim"),
        MoveEntry(moveName = "OD Yoga Flame", notation = "← ↙ ↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Dhalsim"),
        MoveEntry(moveName = "Yoga Teleport", notation = "↓ ↙ ← + P or K", moveType = "Special", associatedCharacter = "Dhalsim"),
        MoveEntry(moveName = "OD Yoga Teleport", notation = "↓ ↙ ← + PP or KK", moveType = "Overdrive", associatedCharacter = "Dhalsim"),
        MoveEntry(moveName = "Yoga Float", notation = "↓ ↓ + K", moveType = "Special", hold = true, associatedCharacter = "Dhalsim"),
        MoveEntry(moveName = "OD Yoga Float", notation = "↓ ↓ + KK", moveType = "Overdrive", hold = true, associatedCharacter = "Dhalsim"),
        MoveEntry(moveName = "SA1 - Yoga Inferno", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Dhalsim"),
        MoveEntry(moveName = "SA2 - Yoga Stream", notation = "← ↙ ↓ ↘ → ← ↙ ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Dhalsim"),
        MoveEntry(moveName = "SA3 - Yoga Sunburst", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Dhalsim"),

        // E. Honda
        MoveEntry(moveName = "Hundred Hand Slap", notation = "P repeatedly", moveType = "Special", associatedCharacter = "E. Honda"),
        MoveEntry(moveName = "OD Hundred Hand Slap", notation = "PP repeatedly", moveType = "Overdrive", associatedCharacter = "E. Honda"),
        MoveEntry(moveName = "Sumo Headbutt", notation = "↓ (charge) ↑ + P", moveType = "Special", hold = true, associatedCharacter = "E. Honda"),
        MoveEntry(moveName = "OD Sumo Headbutt", notation = "↓ (charge) ↑ + PP", moveType = "Overdrive", hold = true, associatedCharacter = "E. Honda"),
        MoveEntry(moveName = "Sumo Smash", notation = "← (charge) → + K", moveType = "Special", hold = true, associatedCharacter = "E. Honda"),
        MoveEntry(moveName = "OD Sumo Smash", notation = "← (charge) → + KK", moveType = "Overdrive", hold = true, associatedCharacter = "E. Honda"),
        MoveEntry(moveName = "Oicho Throw", notation = "(close) ← ↙ ↓ ↘ → + P", moveType = "Special", associatedCharacter = "E. Honda"),
        MoveEntry(moveName = "OD Oicho Throw", notation = "(close) ← ↙ ↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "E. Honda"),
        MoveEntry(moveName = "SA1 - Oni Muso", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "E. Honda"),
        MoveEntry(moveName = "SA2 - Dosukoi Attack", notation = "← ↙ ↓ ↘ → ← ↙ ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "E. Honda"),
        MoveEntry(moveName = "SA3 - Ultimate Killer Head Ram", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "E. Honda"),

        // Guile
        MoveEntry(moveName = "Sonic Boom", notation = "← (charge) → + P", moveType = "Special", hold = true, associatedCharacter = "Guile"),
        MoveEntry(moveName = "OD Sonic Boom", notation = "← (charge) → + PP", moveType = "Overdrive", hold = true, associatedCharacter = "Guile"),
        MoveEntry(moveName = "Flash Kick", notation = "↓ (charge) ↑ + K", moveType = "Special", hold = true, associatedCharacter = "Guile"),
        MoveEntry(moveName = "OD Flash Kick", notation = "↓ (charge) ↑ + KK", moveType = "Overdrive", hold = true, associatedCharacter = "Guile"),
        MoveEntry(moveName = "Spinning Back Knuckle", notation = "← + HP", moveType = "Special", associatedCharacter = "Guile"),
        MoveEntry(moveName = "OD Spinning Back Knuckle", notation = "← + HP + P", moveType = "Overdrive", associatedCharacter = "Guile"),
        MoveEntry(moveName = "SA1 - Sonic Boom Storm", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Guile"),
        MoveEntry(moveName = "SA2 - Sonic Hurricane", notation = "← ↙ ↓ ↘ → ← ↙ ↓ ↘ → + P", moveType = "Super Art", hold = true, associatedCharacter = "Guile"),
        MoveEntry(moveName = "SA3 - Final Flash", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Guile"),

        // Jamie
        MoveEntry(moveName = "Whiskey Shot", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "Jamie"),
        MoveEntry(moveName = "OD Whiskey Shot", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Jamie"),
        MoveEntry(moveName = "Luminous Dive Kick", notation = "(in air) ↓ ↘ → + K", moveType = "Special", associatedCharacter = "Jamie"),
        MoveEntry(moveName = "OD Luminous Dive Kick", notation = "(in air) ↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Jamie"),
        MoveEntry(moveName = "Bakkai", notation = "↓ ↙ ← + P", moveType = "Special", associatedCharacter = "Jamie"),
        MoveEntry(moveName = "OD Bakkai", notation = "↓ ↙ ← + PP", moveType = "Overdrive", associatedCharacter = "Jamie"),
        MoveEntry(moveName = "Tenshin", notation = "← ↓ ↙ + K", moveType = "Special", associatedCharacter = "Jamie"),
        MoveEntry(moveName = "OD Tenshin", notation = "← ↓ ↙ + KK", moveType = "Overdrive", associatedCharacter = "Jamie"),
        MoveEntry(moveName = "SA1 - Soaring Dragon Kick", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Jamie"),
        MoveEntry(moveName = "SA2 - The Devil Inside", notation = "↓ ↙ ← ↓ ↙ ← + P", moveType = "Super Art", associatedCharacter = "Jamie"),
        MoveEntry(moveName = "SA3 - Supreme Dragon Fist", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Jamie"),

        // JP
        MoveEntry(moveName = "Departure", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "JP"),
        MoveEntry(moveName = "OD Departure", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "JP"),
        MoveEntry(moveName = "Trifyla", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "JP"),
        MoveEntry(moveName = "OD Trifyla", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "JP"),
        MoveEntry(moveName = "Torbalan", notation = "↓ ↘ → + K", moveType = "Special", associatedCharacter = "JP"),
        MoveEntry(moveName = "OD Torbalan", notation = "↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "JP"),
        MoveEntry(moveName = "Embrace", notation = "← ↙ ↓ ↘ → + P", moveType = "Special", associatedCharacter = "JP"),
        MoveEntry(moveName = "OD Embrace", notation = "← ↙ ↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "JP"),
        MoveEntry(moveName = "SA1 - Stockpile", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "JP"),
        MoveEntry(moveName = "SA2 - The Great Dictator", notation = "↓ ↙ ← ↓ ↙ ← + P", moveType = "Super Art", associatedCharacter = "JP"),
        MoveEntry(moveName = "SA3 - মহাপralaya", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "JP"),

        // Juri
        MoveEntry(moveName = "Fuhajin", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Juri"),
        MoveEntry(moveName = "OD Fuhajin", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Juri"),
        MoveEntry(moveName = "Saihasho", notation = "(After Fuhajin) → + P", moveType = "Special", associatedCharacter = "Juri"),
        MoveEntry(moveName = "Go Ohsatsu", notation = "(After Fuhajin) → + K", moveType = "Special", associatedCharacter = "Juri"),
        MoveEntry(moveName = "Ankenjaku", notation = "(After Fuhajin) ↑ + K", moveType = "Special", associatedCharacter = "Juri"),
        MoveEntry(moveName = "Kakuyakushu", notation = "(After Fuhajin) ↓ + K", moveType = "Special", associatedCharacter = "Juri"),
        MoveEntry(moveName = "Pinwheel", notation = "↓ ↘ → + K", moveType = "Special", associatedCharacter = "Juri"),
        MoveEntry(moveName = "OD Pinwheel", notation = "↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Juri"),
        MoveEntry(moveName = "Shiku-sen", notation = "(in air) ↓ + K", moveType = "Special", associatedCharacter = "Juri"),
        MoveEntry(moveName = "OD Shiku-sen", notation = "(in air) ↓ + KK", moveType = "Overdrive", associatedCharacter = "Juri"),
        MoveEntry(moveName = "SA1 - Feng Shui Engine", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Juri"),
        MoveEntry(moveName = "SA2 - Kaisen Dankai Raku", notation = "↓ ↙ ← ↓ ↙ ← + K", moveType = "Super Art", associatedCharacter = "Juri"),
        MoveEntry(moveName = "SA3 - Sakkai Fuhazan", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Juri"),

        // Ken
        MoveEntry(moveName = "Hadoken", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "Ken"),
        MoveEntry(moveName = "OD Hadoken", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Ken"),
        MoveEntry(moveName = "Shoryuken", notation = "→ ↓ ↘ + P", moveType = "Special", associatedCharacter = "Ken"),
        MoveEntry(moveName = "OD Shoryuken", notation = "→ ↓ ↘ + PP", moveType = "Overdrive", associatedCharacter = "Ken"),
        MoveEntry(moveName = "Tatsumaki Senpu-kyaku", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Ken"),
        MoveEntry(moveName = "OD Tatsumaki Senpu-kyaku", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Ken"),
        MoveEntry(moveName = "Quick Dash", notation = "→ →", moveType = "Special", associatedCharacter = "Ken"),
        MoveEntry(moveName = "OD Quick Dash", notation = "→ →", moveType = "Overdrive", associatedCharacter = "Ken"),
        MoveEntry(moveName = "Jinrai Kick", notation = "↓ ↘ → + K", moveType = "Special", associatedCharacter = "Ken"),
        MoveEntry(moveName = "OD Jinrai Kick", notation = "↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Ken"),
        MoveEntry(moveName = "SA1 - Tatsumaki Shippu-kyaku", notation = "↓ ↙ ← ↓ ↙ ← + K", moveType = "Super Art", associatedCharacter = "Ken"),
        MoveEntry(moveName = "SA2 - Dragonlash Kick", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Ken"),
        MoveEntry(moveName = "SA3 - The Dragon Awakens", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Ken"),

        // Kimberly
        MoveEntry(moveName = "Spirit Bomb", notation = "↓ ↘ → + P", moveType = "Special", hold = true, associatedCharacter = "Kimberly"),
        MoveEntry(moveName = "OD Spirit Bomb", notation = "↓ ↘ → + PP", moveType = "Overdrive", hold = true, associatedCharacter = "Kimberly"),
        MoveEntry(moveName = "Bushinryu Teleport", notation = "↓ ↓ + K", moveType = "Special", associatedCharacter = "Kimberly"),
        MoveEntry(moveName = "OD Bushinryu Teleport", notation = "↓ ↓ + KK", moveType = "Overdrive", associatedCharacter = "Kimberly"),
        MoveEntry(moveName = "Bushinryu Gale Kick", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Kimberly"),
        MoveEntry(moveName = "OD Bushinryu Gale Kick", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Kimberly"),
        MoveEntry(moveName = "Bushinryu Shadow Step", notation = "(in air) ↓ ↘ → + K", moveType = "Special", associatedCharacter = "Kimberly"),
        MoveEntry(moveName = "OD Bushinryu Shadow Step", notation = "(in air) ↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Kimberly"),
        MoveEntry(moveName = "SA1 - Bushin Beats", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Kimberly"),
        MoveEntry(moveName = "SA2 - Bushin Thunder", notation = "↓ ↙ ← ↓ ↙ ← + K", moveType = "Super Art", associatedCharacter = "Kimberly"),
        MoveEntry(moveName = "SA3 - Bushin Ninjastar Cypher", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Kimberly"),

        // Luke
        MoveEntry(moveName = "Sand Blast", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "Luke"),
        MoveEntry(moveName = "OD Sand Blast", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Luke"),
        MoveEntry(moveName = "Rising Uppercut", notation = "→ ↓ ↘ + P", moveType = "Special", associatedCharacter = "Luke"),
        MoveEntry(moveName = "OD Rising Uppercut", notation = "→ ↓ ↘ + PP", moveType = "Overdrive", associatedCharacter = "Luke"),
        MoveEntry(moveName = "Flash Knuckle", notation = "→ ↘ ↓ ↙ ← + P", moveType = "Special", hold = true, associatedCharacter = "Luke"),
        MoveEntry(moveName = "OD Flash Knuckle", notation = "→ ↘ ↓ ↙ ← + PP", moveType = "Overdrive", hold = true, associatedCharacter = "Luke"),
        MoveEntry(moveName = "Avenger", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Luke"),
        MoveEntry(moveName = "OD Avenger", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Luke"),
        MoveEntry(moveName = "SA1 - Cross Blaster", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Luke"),
        MoveEntry(moveName = "SA2 - Fatal Shot", notation = "↓ ↙ ← ↓ ↙ ← + P", moveType = "Super Art", associatedCharacter = "Luke"),
        MoveEntry(moveName = "SA3 - Giga Buster", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Luke"),

        // Manon
        MoveEntry(moveName = "Pas de Deux", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "Manon"),
        MoveEntry(moveName = "OD Pas de Deux", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Manon"),
        MoveEntry(moveName = "Rond-point", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Manon"),
        MoveEntry(moveName = "OD Rond-point", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Manon"),
        MoveEntry(moveName = "Renverse", notation = "→ ↓ ↘ + K", moveType = "Special", associatedCharacter = "Manon"),
        MoveEntry(moveName = "OD Renverse", notation = "→ ↓ ↘ + KK", moveType = "Overdrive", associatedCharacter = "Manon"),
        MoveEntry(moveName = "Fouetté", notation = "← ↙ ↓ ↘ → + P", moveType = "Special", associatedCharacter = "Manon"),
        MoveEntry(moveName = "OD Fouetté", notation = "← ↙ ↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Manon"),
        MoveEntry(moveName = "SA1 - Étoile", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Manon"),
        MoveEntry(moveName = "SA2 - Batterie", notation = "↓ ↙ ← ↓ ↙ ← + K", moveType = "Super Art", associatedCharacter = "Manon"),
        MoveEntry(moveName = "SA3 - Pas de Trois", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Manon"),

        // Marisa
        MoveEntry(moveName = "Scutum", notation = "→ ↘ ↓ ↙ ← + P", moveType = "Special", associatedCharacter = "Marisa"),
        MoveEntry(moveName = "OD Scutum", notation = "→ ↘ ↓ ↙ ← + PP", moveType = "Overdrive", associatedCharacter = "Marisa"),
        MoveEntry(moveName = "Phalanx", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "Marisa"),
        MoveEntry(moveName = "OD Phalanx", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Marisa"),
        MoveEntry(moveName = "Gladius", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Marisa"),
        MoveEntry(moveName = "OD Gladius", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Marisa"),
        MoveEntry(moveName = "Javelin", notation = "→ ↓ ↘ + P", moveType = "Special", associatedCharacter = "Marisa"),
        MoveEntry(moveName = "OD Javelin", notation = "→ ↓ ↘ + PP", moveType = "Overdrive", associatedCharacter = "Marisa"),
        MoveEntry(moveName = "SA1 - Fate of the Gods", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Marisa"),
        MoveEntry(moveName = "SA2 - Goddess of the Hunt", notation = "↓ ↙ ← ↓ ↙ ← + P", moveType = "Super Art", associatedCharacter = "Marisa"),
        MoveEntry(moveName = "SA3 - Meteorus", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Marisa"),

        // M. Bison
        MoveEntry(moveName = "Psycho Blast", notation = "← (charge) → + P", moveType = "Special", hold = true, associatedCharacter = "M. Bison"),
        MoveEntry(moveName = "OD Psycho Blast", notation = "← (charge) → + PP", moveType = "Overdrive", hold = true, associatedCharacter = "M. Bison"),
        MoveEntry(moveName = "Scissor Kick", notation = "↓ (charge) ↑ + K", moveType = "Special", hold = true, associatedCharacter = "M. Bison"),
        MoveEntry(moveName = "OD Scissor Kick", notation = "↓ (charge) ↑ + KK", moveType = "Overdrive", hold = true, associatedCharacter = "M. Bison"),
        MoveEntry(moveName = "Head Press", notation = "↓ (charge) ↑ + P", moveType = "Special", hold = true, associatedCharacter = "M. Bison"),
        MoveEntry(moveName = "OD Head Press", notation = "↓ (charge) ↑ + PP", moveType = "Overdrive", hold = true, associatedCharacter = "M. Bison"),
        MoveEntry(moveName = "Devil Reverse", notation = "↓ ↘ → + K", moveType = "Special", associatedCharacter = "M. Bison"),
        MoveEntry(moveName = "OD Devil Reverse", notation = "↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "M. Bison"),
        MoveEntry(moveName = "SA1 - Psycho Field", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "M. Bison"),
        MoveEntry(moveName = "SA2 - Psycho Punisher", notation = "← ↙ ↓ ↘ → ← ↙ ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "M. Bison"),
        MoveEntry(moveName = "SA3 - Psycho Crusher", notation = "← (charge) → ← → + K", moveType = "Super Art", hold = true, associatedCharacter = "M. Bison"),

        // Ryu
        MoveEntry(moveName = "Hadoken", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "Ryu"),
        MoveEntry(moveName = "OD Hadoken", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Ryu"),
        MoveEntry(moveName = "Shoryuken", notation = "→ ↓ ↘ + P", moveType = "Special", associatedCharacter = "Ryu"),
        MoveEntry(moveName = "OD Shoryuken", notation = "→ ↓ ↘ + PP", moveType = "Overdrive", associatedCharacter = "Ryu"),
        MoveEntry(moveName = "Tatsumaki Senpu-kyaku", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Ryu"),
        MoveEntry(moveName = "OD Tatsumaki Senpu-kyaku", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Ryu"),
        MoveEntry(moveName = "High Blade Kick", notation = "(in air) ↓ ↘ → + K", moveType = "Special", associatedCharacter = "Ryu"),
        MoveEntry(moveName = "OD High Blade Kick", notation = "(in air) ↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Ryu"),
        MoveEntry(moveName = "Hashogeki", notation = "← ↙ ↓ ↘ → + P", moveType = "Special", associatedCharacter = "Ryu"),
        MoveEntry(moveName = "OD Hashogeki", notation = "← ↙ ↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Ryu"),
        MoveEntry(moveName = "Denjin Charge", notation = "↓ ↙ ← + P", moveType = "Special", associatedCharacter = "Ryu"),
        MoveEntry(moveName = "SA1 - Shinku Hadoken", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Ryu"),
        MoveEntry(moveName = "SA2 - Shin Hashogeki", notation = "← ↙ ↓ ↘ → ← ↙ ↓ ↘ → + P", moveType = "Super Art", hold = true, associatedCharacter = "Ryu"),
        MoveEntry(moveName = "SA3 - Shin Shoryuken", notation = "→ ↓ ↘ → ↓ ↘ + P", moveType = "Super Art", associatedCharacter = "Ryu"),

        // Zangief
        MoveEntry(moveName = "Double Lariat", notation = "P repeatedly", moveType = "Special", associatedCharacter = "Zangief"),
        MoveEntry(moveName = "OD Double Lariat", notation = "PP repeatedly", moveType = "Overdrive", associatedCharacter = "Zangief"),
        MoveEntry(moveName = "Spinning Pile Driver", notation = "(close) ← ↙ ↓ ↘ → ↑ + P", moveType = "Special", associatedCharacter = "Zangief"),
        MoveEntry(moveName = "OD Spinning Pile Driver", notation = "(close) ← ↙ ↓ ↘ → ↑ + PP", moveType = "Overdrive", associatedCharacter = "Zangief"),
        MoveEntry(moveName = "Screw Piledriver", notation = "(close, in air) ↓ ↘ → ↑ + P", moveType = "Special", associatedCharacter = "Zangief"),
        MoveEntry(moveName = "OD Screw Piledriver", notation = "(close, in air) ↓ ↘ → ↑ + PP", moveType = "Overdrive", associatedCharacter = "Zangief"),
        MoveEntry(moveName = "Iron Muscle", notation = "↓ ↙ ← + P", moveType = "Special", associatedCharacter = "Zangief"),
        MoveEntry(moveName = "OD Iron Muscle", notation = "↓ ↙ ← + PP", moveType = "Overdrive", associatedCharacter = "Zangief"),
        MoveEntry(moveName = "SA1 - Cyclone Lariat", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Zangief"),
        MoveEntry(moveName = "SA2 - Bolshoi Russian Suplex", notation = "← ↙ ↓ ↘ → ← ↙ ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Zangief"),
        MoveEntry(moveName = "SA3 - Final Atomic Buster", notation = "(close) ← ↙ ↓ ↘ → ← ↙ ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Zangief"),

        // Akuma
        MoveEntry(moveName = "Gohadoken", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "Akuma"),
        MoveEntry(moveName = "OD Gohadoken", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Akuma"),
        MoveEntry(moveName = "Shoryuken", notation = "→ ↓ ↘ + P", moveType = "Special", associatedCharacter = "Akuma"),
        MoveEntry(moveName = "OD Shoryuken", notation = "→ ↓ ↘ + PP", moveType = "Overdrive", associatedCharacter = "Akuma"),
        MoveEntry(moveName = "Tatsumaki Zankyakku", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Akuma"),
        MoveEntry(moveName = "OD Tatsumaki Zankyakku", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Akuma"),
        MoveEntry(moveName = "Hyakkishu", notation = "↓ ↘ → + K", moveType = "Special", associatedCharacter = "Akuma"),
        MoveEntry(moveName = "OD Hyakkishu", notation = "↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Akuma"),
        MoveEntry(moveName = "Sekia Goshoha", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Akuma"),
        MoveEntry(moveName = "Messatsu Goshoryu", notation = "→ ↓ ↘ → ↓ ↘ + P", moveType = "Super Art", associatedCharacter = "Akuma"),
        MoveEntry(moveName = "Shun Goku Satsu", notation = "P P → ↓ ↘ P K", moveType = "Super Art", associatedCharacter = "Akuma"),

        // Dee Jay
        MoveEntry(moveName = "Air Slasher", notation = "← (charge) → + P", moveType = "Special", hold = true, associatedCharacter = "Dee Jay"),
        MoveEntry(moveName = "OD Air Slasher", notation = "← (charge) → + PP", moveType = "Overdrive", hold = true, associatedCharacter = "Dee Jay"),
        MoveEntry(moveName = "Double Rolling Sobat", notation = "← (charge) → + K", moveType = "Special", hold = true, associatedCharacter = "Dee Jay"),
        MoveEntry(moveName = "OD Double Rolling Sobat", notation = "← (charge) → + KK", moveType = "Overdrive", hold = true, associatedCharacter = "Dee Jay"),
        MoveEntry(moveName = "Jackknife Maximum", notation = "→ ↓ ↘ + K", moveType = "Special", associatedCharacter = "Dee Jay"),
        MoveEntry(moveName = "OD Jackknife Maximum", notation = "→ ↓ ↘ + KK", moveType = "Overdrive", associatedCharacter = "Dee Jay"),
        MoveEntry(moveName = "Machinegun Upper", notation = "P repeatedly", moveType = "Special", associatedCharacter = "Dee Jay"),
        MoveEntry(moveName = "OD Machinegun Upper", notation = "PP repeatedly", moveType = "Overdrive", associatedCharacter = "Dee Jay"),
        MoveEntry(moveName = "SA1 - Sobat Carnival", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Dee Jay"),
        MoveEntry(moveName = "SA2 - Climax Beat", notation = "← ↙ ↓ ↘ → ← ↙ ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Dee Jay"),
        MoveEntry(moveName = "SA3 - Weekend Pleasure", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Dee Jay"),

        // Ed
        MoveEntry(moveName = "Psycho Flicker", notation = "P", moveType = "Special", associatedCharacter = "Ed"),
        MoveEntry(moveName = "OD Psycho Flicker", notation = "PP", moveType = "Overdrive", associatedCharacter = "Ed"),
        MoveEntry(moveName = "Psycho Knuckle", notation = "→ + P", moveType = "Special", associatedCharacter = "Ed"),
        MoveEntry(moveName = "OD Psycho Knuckle", notation = "→ + PP", moveType = "Overdrive", associatedCharacter = "Ed"),
        MoveEntry(moveName = "Psycho Upper", notation = "↓ + P", moveType = "Special", associatedCharacter = "Ed"),
        MoveEntry(moveName = "OD Psycho Upper", notation = "↓ + PP", moveType = "Overdrive", associatedCharacter = "Ed"),
        MoveEntry(moveName = "Psycho Storm", notation = "K", moveType = "Special", associatedCharacter = "Ed"),
        MoveEntry(moveName = "OD Psycho Storm", notation = "KK", moveType = "Overdrive", associatedCharacter = "Ed"),
        MoveEntry(moveName = "SA1 - Psycho Cannon", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Ed"),
        MoveEntry(moveName = "SA2 - Psycho Chamber", notation = "↓ ↙ ← ↓ ↙ ← + P", moveType = "Super Art", associatedCharacter = "Ed"),
        MoveEntry(moveName = "SA3 - The Big Bang", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Ed"),

        // Elena
        MoveEntry(moveName = "Scratch Wheel", notation = "↓ ↘ → + K", moveType = "Special", associatedCharacter = "Elena"),
        MoveEntry(moveName = "OD Scratch Wheel", notation = "↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Elena"),
        MoveEntry(moveName = "Mallet Smash", notation = "→ ↓ ↘ + P", moveType = "Special", associatedCharacter = "Elena"),
        MoveEntry(moveName = "OD Mallet Smash", notation = "→ ↓ ↘ + PP", moveType = "Overdrive", associatedCharacter = "Elena"),
        MoveEntry(moveName = "Spin Scythe", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Elena"),
        MoveEntry(moveName = "OD Spin Scythe", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Elena"),
        MoveEntry(moveName = "Healing", notation = "↓ ↓ + P", moveType = "Special", associatedCharacter = "Elena"),
        MoveEntry(moveName = "OD Healing", notation = "↓ ↓ + PP", moveType = "Overdrive", associatedCharacter = "Elena"),
        MoveEntry(moveName = "SA1 - Healing Wind", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Elena"),
        MoveEntry(moveName = "SA2 - Brave Dance", notation = "↓ ↙ ← ↓ ↙ ← + K", moveType = "Super Art", associatedCharacter = "Elena"),
        MoveEntry(moveName = "SA3 - Skyward Dance", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Elena"),

        // Lily
        MoveEntry(moveName = "Windy Hammer", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "Lily"),
        MoveEntry(moveName = "OD Windy Hammer", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Lily"),
        MoveEntry(moveName = "Condor Spire", notation = "→ ↓ ↘ + K", moveType = "Special", associatedCharacter = "Lily"),
        MoveEntry(moveName = "OD Condor Spire", notation = "→ ↓ ↘ + KK", moveType = "Overdrive", associatedCharacter = "Lily"),
        MoveEntry(moveName = "Condor Dive", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Lily"),
        MoveEntry(moveName = "OD Condor Dive", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Lily"),
        MoveEntry(moveName = "Tomahawk Stream", notation = "← ↙ ↓ ↘ → + P", moveType = "Special", associatedCharacter = "Lily"),
        MoveEntry(moveName = "OD Tomahawk Stream", notation = "← ↙ ↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Lily"),
        MoveEntry(moveName = "SA1 - Breezing Hawk", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Lily"),
        MoveEntry(moveName = "SA2 - Raging Typhoon", notation = "↓ ↙ ← ↓ ↙ ← + K", moveType = "Super Art", associatedCharacter = "Lily"),
        MoveEntry(moveName = "SA3 - Tempest of the Gods", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Lily"),

        // Mai
        MoveEntry(moveName = "Kachosen", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "Mai"),
        MoveEntry(moveName = "OD Kachosen", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Mai"),
        MoveEntry(moveName = "Ryuuenbu", notation = "↓ ↙ ← + P", moveType = "Special", associatedCharacter = "Mai"),
        MoveEntry(moveName = "OD Ryuuenbu", notation = "↓ ↙ ← + PP", moveType = "Overdrive", associatedCharacter = "Mai"),
        MoveEntry(moveName = "Hishouken", notation = "← ↙ ↓ ↘ → + K", moveType = "Special", associatedCharacter = "Mai"),
        MoveEntry(moveName = "OD Hishouken", notation = "← ↙ ↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Mai"),
        MoveEntry(moveName = "Kagerou no Mai", notation = "↓ ↓ + P", moveType = "Special", associatedCharacter = "Mai"),
        MoveEntry(moveName = "OD Kagerou no Mai", notation = "↓ ↓ + PP", moveType = "Overdrive", associatedCharacter = "Mai"),
        MoveEntry(moveName = "SA1 - Chou Hissatsu Shinobibachi", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Mai"),
        MoveEntry(moveName = "SA2 - Mayflower", notation = "↓ ↙ ← ↓ ↙ ← + K", moveType = "Super Art", associatedCharacter = "Mai"),
        MoveEntry(moveName = "SA3 - Houou no Mai", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Mai"),

        // Rashid
        MoveEntry(moveName = "Windy Shot", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "Rashid"),
        MoveEntry(moveName = "OD Windy Shot", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Rashid"),
        MoveEntry(moveName = "Spinning Mixer", notation = "↓ ↙ ← + K", moveType = "Special", associatedCharacter = "Rashid"),
        MoveEntry(moveName = "OD Spinning Mixer", notation = "↓ ↙ ← + KK", moveType = "Overdrive", associatedCharacter = "Rashid"),
        MoveEntry(moveName = "Eagle Spike", notation = "→ ↓ ↘ + K", moveType = "Special", associatedCharacter = "Rashid"),
        MoveEntry(moveName = "OD Eagle Spike", notation = "→ ↓ ↘ + KK", moveType = "Overdrive", associatedCharacter = "Rashid"),
        MoveEntry(moveName = "Arabian Cyclone", notation = "↓ ↘ → + K", moveType = "Special", associatedCharacter = "Rashid"),
        MoveEntry(moveName = "OD Arabian Cyclone", notation = "↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Rashid"),
        MoveEntry(moveName = "SA1 - Ysaar", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Rashid"),
        MoveEntry(moveName = "SA2 - Altair", notation = "↓ ↙ ← ↓ ↙ ← + K", moveType = "Super Art", associatedCharacter = "Rashid"),
        MoveEntry(moveName = "SA3 - Sumerault", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Rashid"),

        // Terry
        MoveEntry(moveName = "Fire Wave", notation = "↓ ↘ → + P", moveType = "Special", associatedCharacter = "Terry"),
        MoveEntry(moveName = "OD Fire Wave", notation = "↓ ↘ → + PP", moveType = "Overdrive", associatedCharacter = "Terry"),
        MoveEntry(moveName = "Rising Tackle", notation = "↓ (charge) ↑ + P", moveType = "Special", hold = true, associatedCharacter = "Terry"),
        MoveEntry(moveName = "OD Rising Tackle", notation = "↓ (charge) ↑ + PP", moveType = "Overdrive", hold = true, associatedCharacter = "Terry"),
        MoveEntry(moveName = "Crack Shoot", notation = "← ↙ ↓ ↘ → + K", moveType = "Special", associatedCharacter = "Terry"),
        MoveEntry(moveName = "OD Crack Shoot", notation = "← ↙ ↓ ↘ → + KK", moveType = "Overdrive", associatedCharacter = "Terry"),
        MoveEntry(moveName = "Power Dunk", notation = "→ ↓ ↘ + K", moveType = "Special", associatedCharacter = "Terry"),
        MoveEntry(moveName = "OD Power Dunk", notation = "→ ↓ ↘ + KK", moveType = "Overdrive", associatedCharacter = "Terry"),
        MoveEntry(moveName = "SA1 - Buster Wolf", notation = "↓ ↘ → ↓ ↘ → + P", moveType = "Super Art", associatedCharacter = "Terry"),
        MoveEntry(moveName = "SA2 - High Angle Geyser", notation = "↓ ↙ ← ↓ ↙ ← + K", moveType = "Super Art", associatedCharacter = "Terry"),
        MoveEntry(moveName = "SA3 - The King of Fighters", notation = "↓ ↘ → ↓ ↘ → + K", moveType = "Super Art", associatedCharacter = "Terry"),
    )
)