package com.example.fightingflow.util

import androidx.compose.runtime.Immutable
import com.example.fightingflow.R
import com.example.fightingflow.model.CharacterEntry
import com.example.fightingflow.model.MoveEntry

@Immutable
class CharacterAndMoveData() {
    val tekkenCharacterEntries:List<CharacterEntry> = listOf(
        CharacterEntry(
            id = 0,
            name = "Alisa",
             imageId = R.drawable.alisa_sprite,
            fightingStyle = "Thruster-Based High-Mobility Fighting Style",
            uniqueMoves = listOf("Clockwork", "Destructive Form", "Boot", "Dual Boot", "Backup").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Anna",
            imageId = R.drawable.anna_sprite,
            fightingStyle = "Aikido based techniques and Koppojutsu based Assassination Arts",
            uniqueMoves = listOf("Backhand Slap", "Hammer Chance", "Chaos Judgement").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Asuka",
            imageId = R.drawable.asuka_sprite,
            fightingStyle = "Kazama Style Traditional Martial Arts",
            uniqueMoves = listOf("Naniwa Gusto").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Azucena",
            imageId = R.drawable.azucena_sprite,
            fightingStyle = "Mixed Martial Arts (Striker)",
            uniqueMoves = listOf("Back Turned", "Libertador", "Nuevo Libertador").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Bryan",
            imageId = R.drawable.bryan_sprite,
            fightingStyle = "Kickboxing",
            uniqueMoves = listOf("Slither Step", "Snake Eyes", "Sway").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Claudio",
            imageId = R.drawable.claudio_sprite,
            fightingStyle = "Sirius Exorcist Arts",
            uniqueMoves = listOf("Starburst").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Clive",
            imageId = R.drawable.clive_sprite,
            fightingStyle = "Dominant",
            uniqueMoves = listOf("Stance1", "Stance2").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Devil Jin",
            imageId = R.drawable.jin_sprite,
            fightingStyle = "Unknown",
            uniqueMoves = listOf("Mishima Crouch Dash (Wind God Step)", "Fly", "Mourning Crow").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Dragunov",
            imageId = R.drawable.dragunov_sprite,
            fightingStyle = "White Reaper",
            uniqueMoves = listOf("Sneak").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Eddy",
            imageId = R.drawable.eddy_sprite,
            fightingStyle = "Capoeira",
            uniqueMoves = listOf("Ginga", "Bananeira", "Negativa", "Mandinga").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Feng",
            imageId = R.drawable.feng_sprite,
            fightingStyle = "Taijiquan",
            uniqueMoves = listOf("Back Turned", "Lingering Shadow", "Shifting Clouds", "Deceptive Step").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Heihachi",
            imageId = R.drawable.heihachi_sprite,
            fightingStyle = "Mishima Style Fighting Karate",
            uniqueMoves = listOf("Raijin Stance").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Hwoarang",
            imageId = R.drawable.hwoarang_sprite,
            fightingStyle = "Taekwondo",
            uniqueMoves = listOf("Crouch Step", "Back Turned", "Right Stance", "Left Stance", "Right Flamingo", "Left Flamingo").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Jack-8",
            imageId = R.drawable.jack8_sprite,
            fightingStyle = "High Tech Annihilator",
            uniqueMoves = listOf("Gamma Howl", "Gamma Charge", "Sit Down").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Jin",
            imageId = R.drawable.jin_sprite,
            fightingStyle = "Karate based on Kyokushin style infused with Devil Gene",
            uniqueMoves = listOf("Awakened Power Stance", "Zenshin and Zanshin", "Breaking Step").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Jun",
            imageId = R.drawable.jun_sprite,
            fightingStyle = "Kazama Style Traditional Martial Arts",
            uniqueMoves = listOf("Izumo", "Genjutsu", "Miare").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Kazuya",
            imageId = R.drawable.kazuya_sprite,
            fightingStyle = "Mishima Style Fighting Karate",
            uniqueMoves = listOf("Devil Form", "Wind God Step").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "King",
            imageId = R.drawable.king_sprite,
            fightingStyle = "Pro Wrestling",
            uniqueMoves = listOf("Beast Step", "Back Turned", "Jaguar Step", "Jaguar Sprint").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Kuma",
            imageId = R.drawable.kuma_sprite,
            fightingStyle = "Heihachi-style Improved Kuma Shinken",
            uniqueMoves = listOf("Hunting", "Bear Sit", "Bear Roll").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Lars", imageId = R.drawable.lars_sprite,
            fightingStyle = "Tekken Forces Martial Arts",
            uniqueMoves = listOf("Avalanche Flip","Dynamic Entry", "Silent Entry", "Limited Entry").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Law",
            imageId =  R.drawable.law_sprite,
            fightingStyle = "Martial Arts",
            uniqueMoves = listOf("Back Turned", "Dragon Charge").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Lee",
            imageId = R.drawable.lee_sprite,
            fightingStyle = "Martial Arts",
            uniqueMoves = listOf("Mist Step", "Hitman").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Leo",
            imageId = R.drawable.leo_sprite,
            fightingStyle = "Baji Quan",
            uniqueMoves = listOf("Lightning Glare", "Jin Bu", "Jin Ji Du Li", "Fo Bu").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Leroy",
            imageId = R.drawable.leroy_sprite,
            fightingStyle = "Wing Chun",
            uniqueMoves = listOf("Hermit").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Lidia",
            imageId = R.drawable.lidia_sprite,
            fightingStyle = "Traditional Karate",
            uniqueMoves = listOf("Horse Stance", "Cat Stance", "Heaven and Earth", "Stalking Wolf Stance").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Lili",
            imageId = R.drawable.lili_sprite,
            fightingStyle = "Self-Taught Style",
            uniqueMoves = listOf("Feisty Rabbit", "Powered Up Feisty Rabbit", "Back Turned", "Dew Glide").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Nina",
            imageId = R.drawable.nina_sprite,
            fightingStyle = "Assassination Arts",
            uniqueMoves = listOf("Ducking Step", "Sway").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Panda",
            imageId = R.drawable.panda_sprite,
            fightingStyle = "Heihachi-style Improved Kuma Shinken",
            uniqueMoves = listOf("Hunting", "Bear Sit", "Bear Roll").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Paul",
            imageId = R.drawable.paul_sprite,
            fightingStyle = "Integrated Martial Arts",
            uniqueMoves = listOf("Cormorant Step", "Deep Dive", "Sway").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Raven",
            imageId = R.drawable.raven_sprite,
            fightingStyle = "Ninjutsu",
            uniqueMoves = listOf("Soulzone", "Shadow Sprint", "Back Turned").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Reina",
            imageId = R.drawable.reina_sprite,
            fightingStyle = "Taido and Mishima-Style Karate",
            uniqueMoves = listOf("Senshin", "Unsoku", "Sentai", "Heaven's Wrath").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Shaheen",
            imageId = R.drawable.shaheen_sprite,
            fightingStyle = "Close Quarters Combat",
            uniqueMoves = listOf("Stealth Step").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Steve",
            imageId = R.drawable.steve_sprite,
            fightingStyle = "Boxing",
            uniqueMoves = listOf("Peekaboo", "Flicker Stance", "Swaying", "Ducking", "Ducking Left", "Ducking Right",
            "Two Faced", "Quick Spin", "Cyclone", "Ducking In", "Lion Heart").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Victor",
            imageId = R.drawable.victor_sprite,
            fightingStyle = "Super Spy CQB",
            uniqueMoves = listOf("Iai", "Perfumer").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Xiaoyu",
            imageId = R.drawable.xiaoyu_sprite,
            fightingStyle = "Chinese Martial Arts",
            uniqueMoves = listOf("Phoenix", "Hypnotist", "Rain Dance").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Yoshimitsu",
            imageId = R.drawable.yoshimitsu_sprite,
            fightingStyle = "Advanced Manji Ninjutsu",
            uniqueMoves = listOf("Bad Stomach", "Mutou No Kiwami", "Death Copter", "Back Turned",
                "Kincho", "Meditation", "Flea", "Flea Step", "Indian Stance", "Healing",
                "Manji Dragonfly").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
        CharacterEntry(
            id = 0,
            name = "Zafina",
            imageId = R.drawable.zafina_sprite,
            fightingStyle = "Ancient Assassination Arts",
            uniqueMoves = listOf("Tarantula", "Scarecrow", "Mantis").toString(),
            gameFranchise = "Tekken",
            gameEntry = "8"
        ),
    )

    val moveEntries = listOf(
        MoveEntry(0, "break", "►", "Break", false, false, false, "Generic"),
        MoveEntry(0, "forward", "f", "Movement", false, false, false, "Generic"),
        MoveEntry(0, "forward_dash", "F", "Movement", false, false, false, "Generic"),
        MoveEntry(0, "down_forward", "d/f", "Movement", false, false, false, "Generic"),
        MoveEntry(0, "down", "d", "Movement", false, false, false, "Generic"),
        MoveEntry(0, "down_back", "d/b", "Movement", false, false, false, "Generic"),
        MoveEntry(0, "back", "b", "Movement", false, false, false, "Generic"),
        MoveEntry(0, "up_back", "u/b", "Movement", false, false, false, "Generic"),
        MoveEntry(0, "up", "u", "Movement", false, false, false, "Generic"),
        MoveEntry(0, "up_forward", "u/f", "Movement", false, false, false, "Generic"),
        MoveEntry(0, "neutral", "n", "Movement", false, false, false, "Generic"),
        MoveEntry(0, "one", "1", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "two", "2", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "three", "3", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "four", "4", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "one_plus_two", "1+2", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "three_plus_four", "3+4", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "one_plus_three", "1+3", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "two_plus_four", "2+4", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "one_plus_four", "1+4", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "two_plus_three", "2+3", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "one_plus_two_plus_three", "1+2+3", "Input", false, false, false, "Generic"),
        MoveEntry(0, "one_plus_two_plus_four", "1+2+4", "Input",  false, false, false,  "Generic"),
        MoveEntry(0, "one_plus_three_plus_four", "1+3+4", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "two_plus_three_plus_four", "2+3+4", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "one_plus_two_plus_three_plus_four", "1+2+3+4", "Input", false, false, false,  "Generic"),
        MoveEntry(0, "Hold", "h", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "Hold Max", "H", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "Delay", "delay", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "Just Frame", "j/f", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "Slide", "(s)", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "Side Switch", "s/s", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "Back Turned", "b/t", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "While Standing", "w/s", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "Crouch", "crouch", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "Dash", "dash", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "Sidestep Left", "s/l", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "Sidestep Right", "s/r", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "Low Parry", "l/p", "Common", false, false, false,  "Generic"),
        MoveEntry(0, "Heat Burst", "h/burst", "Mechanics Input", false, false, false,  "Generic"),
        MoveEntry(0, "Heat Dash", "h/dash", "Mechanic Input", false, false, false,  "Generic"),
        MoveEntry(0, "During Heat", "in heat", "Mechanics Input", false, false, false,  "Generic"),
        MoveEntry(0, "Rage Art", "rage", "Mechanics Input", false, false, false,  "Generic"),
        MoveEntry(0, "Wall Splat", "w/splat", "Stage", false, false, false,  "Generic"),
        MoveEntry(0, "Wall Break", "w/break", "Stage", false, false, false,  "Generic"),
        MoveEntry(0, "Wall Blast", "w/blast", "Stage", false, false, false,  "Generic"),
        MoveEntry(0, "Wall Bounce", "w/bounce", "Stage", false, false, false,  "Generic"),
        MoveEntry(0, "Floor Break", "f/break", "Stage", false, false, false,  "Generic"),
        MoveEntry(0, "Floor Blast", "f/blast", "Stage", false, false, false,  "Generic"),
        MoveEntry(0, "Balcony Break", "b/break", "Stage", false, false, false,  "Generic"),
        MoveEntry(0, "Wind God Step", "WGS", "Mishima", false, false, false,  "Mishima"),
        MoveEntry(0, "Wind God Fist", "WGF", "Mishima", false, false, false,  "Mishima"),
        MoveEntry(0, "Thunder God Fist", "TGF", "Mishima", false, false, false,  "Mishima"),
        MoveEntry(0, "Electric Wind God Fist", "EWGF", "Mishima", false, false, false,  "Mishima"),
        MoveEntry(0, "Omen Thunder God Fist", "OTGF", "Mishima", false, false, false,  "Mishima"),
        MoveEntry(0, "Electric Thunder God Fist", "ETGF", "Mishima", false, false, false,  "Mishima"),
        MoveEntry(0, "Destructive Form", "Destructive Form", "Character", false, false, false,  "Alisa"),
        MoveEntry(0, "Boot", "Boot", "Character", false, false, false,  "Alisa"),
        MoveEntry(0, "Dual Boot", "Dual Boot", "Character", false, false, false,  "Alisa"),
        MoveEntry(0, "Naniwa Gusto", "Naniwa Gusto", "Character", false, false, false,  "Asuka"),
        MoveEntry(0, "Leg Cutter", "Leg Cutter", "Character", false, false, false,  "Asuka"),
        MoveEntry(0, "Libertador", "Libertador", "Character", false, false, false,  "Azucena"),
        MoveEntry(0, "Taking High Attack", "Taking High Attack", "Character", false, false, false,  "Azucena"),
        MoveEntry(0, "Taking Low Attack", "Taking Low Attack", "Character", false, false, false,  "Azucena"),
        MoveEntry(0, "Snake Eyes", "Snake Eyes", "Character", false, false, false,  "Bryan"),
        MoveEntry(0, "Slither Step", "Slither Step", "Character", false, false, false,  "Bryan"),
        MoveEntry(0, "Starburst", "Starburst", "Character", false, false, false,  "Claudio"),
        MoveEntry(0, "Phoenix Shift", "Phoenix Shift", "Character", false, false, false,  "Clive"),
        MoveEntry(0, "Wings Of Light", "Wings Of Light", "Character", false, false, false,  "Clive"),
        MoveEntry(0, "Updraft", "Updraft", "Character", false, false, false,  "Clive"),
        MoveEntry(0, "Zantetsuken", "Zantetsuken", "Character", false, false, false,  "Clive"),
        MoveEntry(0, "Mourning Crow", "Mourning Crow", "Character", false, false, false,  "Devil Jin"),
        MoveEntry(0, "Fly", "Fly", "Character", false, false, false,  "Devil Jin"),
        MoveEntry(0, "Sneak", "Sneak", "Character", false, false, false,  "Dragunov"),
        MoveEntry(0, "Ginga", "Ginga", "Character", false, false, false,  "Eddy"),
        MoveEntry(0, "Bananeira", "Bananeira", "Character", false, false, false,  "Eddy"),
        MoveEntry(0, "Negativa", "Negativa", "Character", false, false, false,  "Eddy"),
        MoveEntry(0, "Mandinga", "Mandinga", "Character", false, false, false,  "Eddy"),
        MoveEntry(0, "Deceptive Step", "Deceptive Step", "Character", false, false, false,  "Feng"),
        MoveEntry(0, "Shifting Clouds", "Shifting Clouds", "Character", false, false, false,  "Feng"),
        MoveEntry(0, "Wind God's Kamae", "Wind God's Kamae", "Character", false, false, false,  "Heihachi"),
        MoveEntry(0, "Thunder God's Kamae", "Thunder God's Kamae", "Character", false, false, false,  "Heihachi"),
        MoveEntry(0, "Warrior Instinct", "Warrior Instinct", "Character", false, false, false,  "Heihachi"),
        MoveEntry(0, "Right Stance", "Right Stance", "Character", false, false, false,  "Hwoarang"),
        MoveEntry(0, "Left Stance", "Left Stance", "Character", false, false, false,  "Hwoarang"),
        MoveEntry(0, "Right Flamingo", "Right Flamingo", "Character", false, false, false,  "Hwoarang"),
        MoveEntry(0, "Left Flamingo", "Left Flamingo", "Character", false, false, false,  "Hwoarang"),
        MoveEntry(0, "Sit Down", "Sit Down", "Character", false, false, false,  "Jack-8"),
        MoveEntry(0, "Gamma Howl", "Gamma Howl", "Character", false, false, false,  "Jack-8"),
        MoveEntry(0, "Zenshin", "Zenshin", "Character", false, false, false,  "Jin"),
        MoveEntry(0, "Izumo", "Izumo", "Character", false, false, false,  "Jun"),
        MoveEntry(0, "Genjutsu", "Genjutsu", "Character", false, false, false,  "Jun"),
        MoveEntry(0, "Miare", "Miare", "Character", false, false, false,  "Jun"),
        MoveEntry(0, "Hunting", "Hunting", "Character", false, false, false,  "Kuma & Panda"),
        MoveEntry(0, "Bear Sit", "Bear Sit", "Character", false, false, false,  "Kuma & Panda"),
        MoveEntry(0, "Bear Roll", "Bear Roll", "Character", false, false, false,  "Kuma & Panda"),
        MoveEntry(0, "Dynamic Entry", "Dynamic Entry", "Character", false, false, false,  "Lars"),
        MoveEntry(0, "Silent Entry", "Silent Entry", "Character", false, false, false,  "Lars"),
        MoveEntry(0, "Limited Entry", "Limited Entry", "Character", false, false, false,  "Lars"),
        MoveEntry(0, "Dragon Charge", "Dragon Charge", "Character", false, false, false,  "Law"),
        MoveEntry(0, "Hitman", "Hitman", "Character", false, false, false,  "Lee"),
        MoveEntry(0, "Jin Ji Du Li", "Jin Ji Du Li", "Character", false, false, false,  "Leo"),
        MoveEntry(0, "Fo Bu", "Fo Bu", "Character", false, false, false,  "Leo"),
        MoveEntry(0, "Hermit", "Hermit", "Character", false, false, false,  "Leroy"),
        MoveEntry(0, "Horse Stance", "Horse Stance", "Character", false, false, false,  "Lidia"),
        MoveEntry(0, "Cat Stance", "Cat Stance", "Character", false, false, false,  "Lidia"),
        MoveEntry(0, "Heaven and Earth", "Heaven and Earth", "Character", false, false, false,  "Lidia"),
        MoveEntry(0, "Stalking Wolf Stance", "Stalking Wolf Stance", "Character", false, false, false,  "Lidia"),
        MoveEntry(0, "Dew Glide", "Dew Glide", "Character", false, false, false,  "Lili"),
        MoveEntry(0, "Soulzone", "Soulzone", "Character", false, false, false,  "Raven"),
        MoveEntry(0, "Unsoku", "Unsoku", "Character", false, false, false,  "Reina"),
        MoveEntry(0, "Sentai", "Sentai", "Character", false, false, false,  "Reina"),
        MoveEntry(0, "Heaven's Wrath", "Heaven's Wrath", "Character", false, false, false,  "Reina"),
        MoveEntry(0, "Stealth Step", "Stealth Step", "Character", false, false, false,  "Shaheen"),
        MoveEntry(0, "Quick Spin", "Quick Spin", "Character", false, false, false,  "Steve"),
        MoveEntry(0, "Ducking", "Ducking", "Character", false, false, false,  "Steve"),
        MoveEntry(0, "Peekaboo", "Peekaboo", "Character", false, false, false,  "Steve"),
        MoveEntry(0, "Ducking In", "Ducking In", "Character", false, false, false,  "Steve"),
        MoveEntry(0, "Ducking Left", "Ducking Left", "Character", false, false, false,  "Steve"),
        MoveEntry(0, "Ducking Right", "Ducking Right", "Character", false, false, false,  "Steve"),
        MoveEntry(0, "Flicker Stance", "Flicker Stance", "Character", false, false, false,  "Steve"),
        MoveEntry(0, "Swaying", "Swaying", "Character", false, false, false,  "Steve"),
        MoveEntry(0, "Lion Heart", "Lion Heart", "Character", false, false, false,  "Steve"),
        MoveEntry(0, "Iai", "Iai", "Character", false, false, false,  "Victor"),
        MoveEntry(0, "Perfumer", "Perfumer", "Character", false, false, false,  "Victor"),
        MoveEntry(0, "Phoenix", "Phoenix", "Character", false, false, false,  "Xiaoyu"),
        MoveEntry(0, "Hypnotist", "Hypnotist", "Character", false, false, false,  "Xiaoyu"),
        MoveEntry(0, "Kincho", "Kincho", "Character", false, false, false,  "Yoshimitsu"),
        MoveEntry(0, "Mutou No Kiwami", "Mutou No Kiwami", "Character", false, false, false,  "Yoshimitsu"),
        MoveEntry(0, "Manji Dragonfly", "Manji Dragonfly", "Character", false, false, false,  "Yoshimitsu"),
        MoveEntry(0, "Flea", "Flea", "Character", false, false, false,  "Yoshimitsu"),
        MoveEntry(0, "Indian Stance", "Indian Stance", "Character", false, false, false,  "Yoshimitsu"),
        MoveEntry(0, "Tarantula", "Tarantula", "Character", false, false, false,  "Zafina"),
        MoveEntry(0, "Scarecrow", "Scarecrow", "Character", false, false, false,  "Zafina"),
        MoveEntry(0, "Mantis", "Mantis", "Character", false, false, false,  "Zafina"),
    )
//    val consoleButtons = listOf(
//        MoveEntry(0, "×", "Console", "Playstation"),
//        MoveEntry(0, "○", "Console", "Playstation"),
//        MoveEntry(0, "△", "Console", "Playstation"),
//        MoveEntry(0, "□", "Console", "Playstation"),
//        MoveEntry(0, "R1", "Console", "Playstation"),
//        MoveEntry(0, "R2", "Console", "Playstation"),
//        MoveEntry(0, "R3", "Console", "Playstation"),
//        MoveEntry(0, "L1", "Console", "Playstation"),
//        MoveEntry(0, "L2", "Console", "Playstation"),
//        MoveEntry(0, "L3", "Console", "Playstation"),
//        MoveEntry(0, "A", "Console", "Xbox"),
//        MoveEntry(0, "B", "Console", "Xbox"),
//        MoveEntry(0, "X", "Console", "Xbox"),
//        MoveEntry(0, "Y", "Console", "Xbox"),
//        MoveEntry(0, "RB", "Console", "Xbox"),
//        MoveEntry(0, "RT", "Console", "Xbox"),
//        MoveEntry(0, "RS", "Console", "Xbox"),
//        MoveEntry(0, "LB", "Console", "Xbox"),
//        MoveEntry(0, "LS", "Console", "Xbox"),
//        MoveEntry(0, "LS", "Console", "Xbox")
//    )
}